# NOTE: This Dockerfile is based on CUDA 12.1.
# To benchmark on other CUDA versions, search and replace "12.1" and "121".
FROM nvidia/cuda:12.1.0-devel-ubuntu22.04

SHELL ["/bin/bash", "-ec"]

# Step 1. Set up Ubuntu
# NOTE: libcuda.so.1 doesn't exist in NVIDIA's base image, link the stub file to work around
RUN grep -v '[ -z "\$PS1" ] && return' ~/.bashrc >/tmp/bashrc                                 && \
    mv /tmp/bashrc ~/.bashrc                                                                  && \
    echo "export MLC_HOME=/mlc_llm/" >>~/.bashrc                                              && \
    echo "export PATH=/usr/local/cuda/bin/:\$PATH" >>~/.bashrc                                && \
    ln -s /usr/local/cuda/lib64/stubs/libcuda.so /usr/lib/x86_64-linux-gnu/libcuda.so.1       && \
    apt update                                                                                && \
    apt install --yes wget curl git vim build-essential openssh-server

# Step 2. Set up python, including TVM Unity
RUN bash <(curl -L micro.mamba.pm/install.sh) && source ~/.bashrc       && \
    micromamba create --yes -n python311 -c conda-forge                    \
    python=3.11 "cmake>=3.24"                                              \
    pytorch-cpu rust sentencepiece protobuf                             && \
    micromamba activate python311                                       && \
    pip install --pre mlc-ai-nightly-cu121 -f https://mlc.ai/wheels

# Step 3. Compile MLC command line
# TODO: Provide prebuilt for `mlc_chat_cli` on CUDA
RUN source ~/.bashrc && micromamba activate python311                   && \
    git clone --recursive https://github.com/mlc-ai/mlc-llm/ $MLC_HOME  && \
    cd $MLC_HOME && mkdir build && cd build && touch config.cmake       && \
    echo "set(CMAKE_BUILD_TYPE RelWithDebInfo)" >>config.cmake          && \
    echo "set(CMAKE_EXPORT_COMPILE_COMMANDS ON)" >>config.cmake         && \
    echo "set(USE_CUDA ON)" >>config.cmake                              && \
    echo "set(USE_VULKAN OFF)" >>config.cmake                           && \
    echo "set(USE_METAL OFF)" >>config.cmake                            && \
    echo "set(USE_OPENCL OFF)" >>config.cmake                           && \
    cmake .. && make -j$(nproc)

# Step 4. Set up SSH and clean up
COPY install/ssh.sh /install/ssh.sh
RUN bash /install/ssh.sh && rm /usr/lib/x86_64-linux-gnu/libcuda.so.1
WORKDIR /root
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
